### PR TITLE
Update to ClojureScript 0.0-3211

### PR DESCRIPTION
**Pull request by mfikes**
- Update Clojure to 1.7.0-beta1 (used by ClojureScript 0.0-3211)
- Update other deps to latests releases
- Add new symbols to setup.clj
- Add support for reader conditionals
- Re-generate cljs and js files in resource

### CODE REVIEW

**Comment by mfikes** [comment]
@fogus The only "human-made" changes are to 3 files: `project.clj`, `setup.clj`, and `service.clj`. Everything else is churn due to re-generating the stuff in `resources`. Fortunately `project.clj` appears at the top of the GitHub diff view, and `setup.clj` and `service.clj` appear at the very bottom.

**Comment by mfikes** [comment]
In terms of testing, this codebase is running on http://geit.fikesfarm.com, where it has processed 1700 compile requests. (`POST /compile`)

**Comment by fogus** [comment]
Thank you!  I'll try to push it out this Friday.

**Comment by fogus** [comment]
So the latest on this is that Himera is not deploying to Heroku, and I haven't had enough cycles to devote to figuring out why.  The specific error that it's running into is:

    Exception in thread "main" java.util.regex.PatternSyntaxException: Unknown inline modifier near index 2

If you have any ideas what's causing this then I'd be happy to learn more.

**Comment by mfikes** [comment]
There is a regular expression `#"(?U)^[\p{Alpha}_$]"` [here](https://github.com/clojure/clojurescript/blob/159fad2df02efd869842076fef22b51de3a6c085/src/main/clojure/cljs/util.cljc#L159) that requires Java 7 or later.

Specifically “The UNICODE_CHARACTER_CLASS mode can also be enabled via the embedded flag expression (?U).", [ref](http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#UNICODE_CHARACTER_CLASS).

If you fire up a REPL with Java 6, you can cause an error which I suspect is reproducing the problem exhibited in Heroku:
```
user=> #"(?U)^[\p{Alpha}_$]"

PatternSyntaxException Unknown inline modifier near index 2
(?U)^[\p{Alpha}_$]
  ^  java.util.regex.Pattern.error (Pattern.java:1713)
```

**Comment by fogus** [comment]
Downgraded my Heroku app to Java7 and deployed.  So far, so good at http://himera.herokuapp.com/index.html

**Pull request merged**
